chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

fishshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .router import router
from rest_framework.authtoken import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
    path('user/', include('user.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('home/', include('home.urls', namespace='home')),
    path('api/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
    path('chat/', include('chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('dashboard/', views.dashboard, name='dashboard'),
    ]
    

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_history/<int:order_id>/', views.order_history_detail, name='order_history_detail'),
    path('order_history/', views.order_history_list, name='order_history_list')
    ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('recipe/', views.recipe_list, name='recipe_list'),
    path('recipe/<slug:category_slug>/', views.recipe_list, name='recipe_category'),
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('<slug:category_slug>/', views.product_list, name='product_category'),
    path('answers/<int:q_id>/', views.q_and_a, name='staff_answer'),
    path('', views.product_list, name='product_list'),
    
    ]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.log_in, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logged_out.html'), name='logout'),
    path('account_creation/', views.account_creation, name='account_creation'),
    ]

home/models.py
from django.db import models

# Create your models here.
class Team(models.Model):
    name = models.CharField(max_length=250)
    role = models.CharField(max_length=250)
    bio = models.TextField()
    profile_image = models.ImageField(upload_to='home/profile_image', blank=True)

home/views.py
from django.shortcuts import render
from home.models import Team
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def dashboard(request):
    user_name = request.user.username
    context = {
        'user_name': user_name
    }
    return render(request, 'home/dashboard.html', context)

def about(request):
    team = Team.objects.all()
    context = {
        'team': team
    }
    return render(request, 'home/about.html', context)

home/templates/home/about.html
{% extends 'home/base.html' %}

{% block title %}
About
{% endblock %}

{% block content %}

<p>
    <h1> Description Title</h1>
    <h3> Description Text </h3>
    
</p>

<p>
    {% for member in team %}
    <img src="{{member.profile_image.url}}" style='width:45px; height:45px'/>
    {{member.name}}
    {{member.role}}
    {{member.bio}}
    {% empty %}
    There is nothing here
    {% endfor %}
</p>

{% endblock %}

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            
            {% block title %}
            {% endblock %}
        </title>
        <link rel='stylesheet' type='text/css' href='{% static "css/main.css" %}'>
        <link href='https://fonts.googleapis.com/css?family=Alex Brush' rel='stylesheet'>
        {% block bootstrap %}
        {% endblock %}
    </head>
    
    <body class='body-detail'>
        <header class='header'>
            <nav class='nav-bar'>
                <div class='nav-bars'>
                <ul class='nav-top'>
                    <li><a href='{% url "store:product_list" %}'>Store</a></li>
                    <li><a href='{% url "orders:cart" %}'> Shopping Cart</a></li>
                    {% if user.is_authenticated %}
                    <li><a href='{% url "user:logout" %}'> Logout </a></li>
                    {% else %}
                    <li><a href='{% url "user:login" %}'> Login </a></li>
                    <li><a href='{% url "user:account_creation" %}'>Create Account</a></li>
                    {% endif %}
                </ul>
                </div>
            </nav>
        </header>
        <div class='container'>
        {% block content %}
        {% endblock %}
        </div>
        {% block bsjs %}
        {% endblock %}
    </body>
</html>

home/templates/home/dashboard.html
{% extends 'home/base.html' %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<div class="flex-box column">
    <div>
        <h1>
            Dashboard
        </h1>
    </div>
    <div>
        <h2>
            Welcome back {{user_name}}
        </h2>
    </div>

</div>

{% endblock %}