chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

fishshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .router import router
from rest_framework.authtoken import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
    path('user/', include('user.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('home/', include('home.urls', namespace='home')),
    path('api/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
    path('chat/', include('chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_history/<int:order_id>/', views.order_history_detail, name='order_history_detail'),
    path('order_history/', views.order_history_list, name='order_history_list')
    ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('recipe/', views.recipe_list, name='recipe_list'),
    path('recipe/<slug:category_slug>/', views.recipe_list, name='recipe_category'),
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('<slug:category_slug>/', views.product_list, name='product_category'),
    path('answers/<int:q_id>/', views.q_and_a, name='staff_answer'),
    path('', views.product_list, name='product_list'),
    
    ]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.log_in, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logged_out.html'), name='logout'),
    path('account_creation/', views.account_creation, name='account_creation'),
    ]

store/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.urls import reverse
from django.contrib.auth.models import User

from ckeditor.fields import RichTextField



#from streams import blocks  

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.CharField(max_length=200, null=True)
    category_image = models.ImageField(upload_to='store/category/', null=True)
    
    def get_absolute_url(self):
        return reverse('store:product_category', args=[self.slug])
        
    def get_absolute_url_recipe(self):
        return reverse('store:recipe_category', args=[self.slug])
        
    def __str__(self):
        return '%s' % (self.name)
    
class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='product_category')
    product_name = models.CharField(max_length=250)
    product_quantity = models.IntegerField()
    product_price = models.FloatField()
    product_description = models.TextField()
    product_image = models.ImageField(upload_to='store/product/', blank=True)
    avaliable = models.BooleanField(default=True)
    
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.id])

    
    def __str__(self):
        return '%s' % (self.product_name)
    
        

    def image(self):
        """
        for admin thumb nail pic thing
        """
        
        if self.product_image:
            return mark_safe('<img src="%s" style="width: 45px; height: 45px" />' % self.product_image.url)
        else:
            return 'No image found'
            
    image.short_description = 'Image'
    
    
class Fish_Recipe(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='recipe_product', blank=False, null=True)
    title = models.CharField(max_length=200, blank=False, null=True)
    text = RichTextField(blank=True, null=True)
    
    class Meta:
        verbose_name = 'Fish Recipe'
        verbose_name_plural = 'Fish Recipes'
        
    
        
class QandA(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_QandA', blank=False, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_QandA', null=True)
    question = models.CharField(max_length=200, blank=False, null=False)
    answer = models.TextField()
    staff_user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    
    class Meta:
        verbose_name = ' Q and A'
        verbose_name_plural = 'Qs and As'

store/forms.py
from django import forms

class QandAForms(forms.Form):
    question = forms.CharField(max_length=100, required=True)
    
"""
    def __init__(self, user, *args, **kwargs):
        super(QandAForms, self).__init__(*args, **kwargs)
        self.fields['user'].initial = user
        self.fields['user'].disabled = True
"""        
    
class AnswerForm(forms.Form):
    answer = forms.CharField(max_length=250, required=True)

store/views.py
from django.shortcuts import render, get_object_or_404
from store.models import Product, Category, Fish_Recipe, QandA
from orders.forms import QuantityForm
from store.forms import QandAForms, AnswerForm
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(avaliable=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {'categories': categories,
               'products': products,
              }
    return render(request, 'store/item_list.html', context)


def product_detail(request, id):
    product = get_object_or_404(Product, id=id, avaliable=True)
    quantity_form = QuantityForm(id)
    qa = QandA.objects.filter(product__id=id)
    similar_products = get_similar_product(id)
    if request.method == 'POST':
        form = QandAForms(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            q_and_a = QandA.objects.create(product=product,
                                           user=request.user,
                                           question=cd['question'])
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            return HttpResponse('it went wrong')
                                           
    question_form = QandAForms()
    answer_form = AnswerForm()
    context = {
        'product': product,
        'quantity_form': quantity_form,
        'qa': qa,
        'question_form': question_form,
        'answer_form': answer_form,
        'similar_products': similar_products
        
    }
    try:
        context['recipe'] = Fish_Recipe.objects.get(product=product)
    except ObjectDoesNotExist:
        pass
        
        
    return render(request, 'store/item_detail.html', context)
    
def get_similar_product(product_id):
    category_ids = list(Product.objects.filter(id=product_id).values_list(
                                                str('category__id'), flat=True))
    category = Category.objects.filter(id__in=category_ids)
    similar_product = Product.objects.filter(
                    category__in = category).distinct().exclude(id=product_id)[0:5]
    return similar_product



def recipe_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    recipe = Fish_Recipe.objects.all()
    products = Product.objects.filter(avaliable=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
        recipe = Fish_Recipe.objects.filter(product__in=products)
    context = {'categories': categories,
               'products': products,
               'recipe': recipe,
              }
    return render(request, 'store/recipe_list.html', context)
# Create your views here.

@staff_member_required
def q_and_a(request, q_id):
    if request.method == 'POST':
        q_n_a = QandA.objects.get(id=q_id)
        form = AnswerForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            q_n_a.answer = cd['answer']
            q_n_a.staff_user = request.user
            q_n_a.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
   



"""

"""
    
            

store/templates/store/item_detail.html
{% extends 'home/base.html' %}

{% block title %}
{{product.name}}
{% endblock %}

{% block content %}
<div class="product-detail-box">
    <div class='product-flex'>
        <div class='product-grid-detail'>
    
            <div class='product-image'>
                <img src="{{product.product_image.url}}">
            </div>
            <div class='product-title'>
                <p>{{product.product_name}}</p>
            </div>
            <div class='product-information'>
                <p>{{product.product_description}}</p>
                {% if recipe %}
                <p>Recipe to be finished</p>
                {% endif %}
            </div>
            <div class='product-orders'>
                <p>${{product.product_price}}</p> 
                <form action='{% url "orders:add" product.id %}' method='post'>
                    {% csrf_token %}
                    {{quantity_form}} of {{product.product_quantity}}
                    <input type="submit" value="Submit"/>
                </form>
            </div>
        </div>
    </div>
    <div class="product-under column">
        <div class='similar-products column'>
            {% if similar_products %}
            <div class='flex-box'>
                <p> See Similar Products </p>
            </div>
            <div class='flex-box'>
                {% for product in similar_products %}
                <div class='similar-products-grid'>
                    <img src="{{product.product_image.url}}" style='with:150px; height:150px'>
                    <p>{{product.product_name}}</p>
                    <p>${{product.product_price}}</p>
                </div>
                {% endfor %}
                {% endif %}
            </div>    
        </div>
        <div class='flex-box column'>
            {% for q in qa %}
            <p><b>Question</b></p>
            <p class='small'>User: {{q.user}}</p>
            <p class='small'>Question: {{q.question}}</p>
            {% if q.answer %}
            <p class="small"><b>Answer</b></p>
            <p>             {{q.staff_user}}         </p>
                            {{q.answer }}
            {% else %}
            <p>
                
                    {% if request.user.is_staff %}
                    <p><b>Staff Answer here</b></p>
                    <form action='{% url "store:staff_answer" q.id %}' method='post'>
                        {% csrf_token %}
                        <p>
                            {{ answer_form }}
                        </p>
                        <input type='submit' value='submit'>
                    </form>
            </p>
            {% endif %}
            {% endif %}
            {% empty %}
            <p>There are no questions yet</p>
            {% endfor %}
            
            {% if user.is_authenticated %}
            {% if user.is_staff %}
            {% else %}
            <p><b> Questions and Answers</b></p>
            <form action='{% url "store:product_detail" product.id %}' method='POST'>
                {% csrf_token %}
                {{question_form.as_p}}
                <input type='submit' value='submit'>
            </form>
            {% endif %}
            {% else %}
            <p>Please <a href="{% url "user:login" %}?next={{request.path}}">Login</a> to submit a question
            </p>
            {% endif %}
        </div>
        

    </div>
</div>
{% endblock %}

store/templates/store/item_list.html
{% extends 'home/base.html' %}

{% block title %}
Product List
{% endblock %}

{% block content %}
<div class='store-list'>
    <div class='flex-box column minwidth'>
        <div class='flex-box column store-margin'>
            <div class= 'flex-box store-banner'>
                <h1 class='store-title'> Uncle's Website</h1>
            </div>
            <div class='flex-box store-banner-items'>
                <ul class='banner-options'>
                    <li>
                        <a href='{% url "store:product_list" %}'> All </a>
                    </li>
                    {% for c in categories %}
                    <li>
                        <a href='{{c.get_absolute_url }}'>{{c.name}}</a>
                    </li>
                    {% endfor %}
                </ul>
                
            </div>
        </div>
        <div class='flex-box products-flex'>
            <div class='categories-box'>
                <h3> Category </h3>
                <ul>
                    <li>
                        <a href='{% url "store:product_list" %}'>All</a>
                    </li>
                    {% for c in categories %}
                    <li>
                        <a href='{{c.get_absolute_url }}'>{{c.name}}</a>
                
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class='products-box'>
                <div class='products'>
                {% for product in products %}
                    <div class='product-detail'>
                        <div class='flex-box justify-content-center'>
                            <img src='{{product.product_image.url}}' style='wdth:150px; height:150px' />
                        </div>
                        <div class='flex-box justify-content-center'>
                        <a href={{product.get_absolute_url}}>{{product.product_name}}</a>
                        </div>
                        <div class='flex-box justify-content-center'>
                            ${{product.product_price}}
                        </div>
                        <div class='flex-box justify-content-center'>
                            {% if product.product_quantity == 0 %}
                            Currently Soldout
                            {% endif %}
                        </div>
                    </div>
                {% empty %}
                    <h3>
                    No Product Shown
                    </h3>
                {% endfor %}
                <div>
            </div>        
        </div>
    </div>
</div>

{% endblock %}

store/templates/store/recipe_detail_page.html
{% extends 'home/base.html' %}

{% block content %}
{{self}}
{{self.product}}
{% endblock %}

store/templates/store/recipe_list.html
{% extends 'home/base.html' %}

{% block title %}
Product List
{% endblock %}

{% block content %}

<ul>
    <li>
        <a href='{% url "store:recipe_list" %}'>All</a>
    </li>
    {% for c in categories %}
    <li>
        <a href='{{c.get_absolute_url_recipe }}'>{{c.name}}</a>

    </li>
    {% endfor %}
</ul>


{% for r in recipe %}
<img src='{{r.product.product_image.url}}' style='with:100px; height:100px' />
<p><a href={{r.product.get_absolute_url}}>{{r.product.product_name}}</a></p>
<p>{{r.title}}</p>




{% empty %}
<h3>
    No Recipe Here
</h3>
{% endfor %} 

{% endblock %}

store/templates/store/store_listing_page.html
{% extends 'home/base.html' %}

{% block content %}
{{self}}
{% for product in products %}]
{{product}}

{% endfor %}

{% endblock %}

store/templates/store/store_page.html
{% extends "home/base.html" %}

{% load wagtailcore_tags %}

{% block body_class %}template-blogpage{% endblock %}

{% block content %}
    <h1>{{ page.title }}</h1>
    <p class="meta">{{ page.date }}</p>

    <div class="intro">{{ page.intro }}</div>

    {{ page.body|richtext }}

    <p><a href="{{ page.get_parent.url }}">Return to blog</a></p>

{% endblock %}