chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

fishshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .router import router
from rest_framework.authtoken import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
    path('user/', include('user.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('home/', include('home.urls', namespace='home')),
    path('api/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
    path('chat/', include('chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_history/<int:order_id>/', views.order_history_detail, name='order_history_detail'),
    path('order_history/', views.order_history_list, name='order_history_list')
    ]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from store.models import Product
from django.utils.html import format_html

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250, blank=True)
    email = models.EmailField(blank=True)
    address = models.CharField(max_length=250, blank=True)
    postal_code = models.CharField(max_length=250, blank=True)
    city = models.CharField(max_length=250, blank=True)
    
    def __str__(self):
        return 'Order {}'.format(self.user)
        
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.orders_items.all())
        

class Order(models.Model):
    paid = models.BooleanField(default=False)
    total_price = models.DecimalField(max_digits=5, decimal_places=2)
    create = models.DateTimeField(auto_now_add=True)
    user_info = models.ForeignKey(UserInfo, on_delete=models.CASCADE, related_name='user_infos', null=True)
    

"""
may need to add is it sent
"""


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_orderitem', null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orders_product')
    price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return '{}'.format(self.product)
        
        
    def get_cost(self):
        return self.price * self.quantity



    

orders/forms.py
from django import forms
from store.models import Product, QandA
from orders.models import UserInfo
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404




class QuantityForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ('product_quantity',)

    def __init__(self, id, *args, **kwargs):
        super(QuantityForm, self).__init__(*args, **kwargs)
        quantity = get_object_or_404(Product, id=id)
        quantity = quantity.product_quantity
        choice = [(i, str(i)) for i in range(1, quantity+1)]
        self.fields['product_quantity'].widget = forms.Select(choices=choice)
        
    """
    May be Change widget to typing version
    """
    
class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['user', 'first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city']

    def __init__(self, *args, **kwargs):
        super(UserInfoForm, self).__init__(*args, **kwargs)
        self.fields['user'].disabled = True

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from orders.cart import Cart
from store.models import Product
from orders.forms import QuantityForm, UserInfoForm
from orders.models import Order, OrderItem, UserInfo
from django.http import HttpResponse
# Create your views here.

"""
Change Quantity in Cart
Add remove item from template
"""

def cart_detail(request):
    """get cart detail"""
    cart = Cart(request)
    context = {
        'cart': cart,
    }
    return render(request, 'orders/cart.html', context)
    
def add_to_cart(request, product_id):
    cart = Cart(request)
    product_object = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        forms = QuantityForm(product_id, request.POST)
        if forms.is_valid():
            cd = forms.cleaned_data
            cart.add(product=product_object, quantity=cd['product_quantity']
                                             )
                                             
    return redirect('orders:cart')
        
    
def remove_from_cart(request, product_id):
    """remove cart item"""
    cart = Cart(request)
    product_object = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        cart.remove(product_object)
        cart.save_session()
    return redirect('orders:cart')


    
def checkout(request):
    """checkout process"""
    cart = Cart(request)
    if request.method == 'POST':
        form = UserInfoForm(request.POST, instance=request.user.userinfo)
        if form.is_valid():
            form.save()
            order_total = cart.get_total_price()
            get_order = Order.objects.create(paid=False,
                                                 total_price=order_total)
            get_userinfo = UserInfo.objects.get(user=request.user)
            get_order.user_info = get_userinfo
            get_order.save()
            for item in cart:
                create_item = OrderItem.objects.create(
                                         order = get_order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'],
                                         )
                cart.stock_management(item['product'], item['quantity'])
            cart.clear()
            return redirect('home:dashboard')
            
            
    form = UserInfoForm(instance=request.user.userinfo)
    context = {
        'form': form,
    }
    return render(request, 'orders/checkout.html', context)


def order_history_detail(request, order_id):
    order_history_list = {}
    orders = Order.objects.get(id=order_id)
    order_items = OrderItem.objects.filter(order=orders)
    for order in order_items:
        order_history_list[str(order.id)] = order
    
    context = {
        'order': orders,
        'order_history': order_history_list
    }
    return render(request, 'orders/order_history_detail.html', context)
    
def order_history_list(request):
    user = UserInfo.objects.get(user=request.user)
    orders = Order.objects.filter(user_info=user)
    context = {
        'order_history': orders,
    }
    return render(request, 'orders/order_history.html', context)

orders/templates/orders/cart.html
{% extends 'home/base.html' %}

{% block title %}
Cart
{% endblock %}


{% block content %}
<div class='flex-box'>
    <div class='flex-box column table-width'>
        <div>
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                
                    <table>
                        <thead>
                            <tr class='table-head'>
                                <th class='column1'>Item</th>
                                <th class='column5'></th>
                                <th class='column2'>Quantity</th>
                                <th class='column3'>Individual Price</th>
                                <th class='column4'>Total Price</th>
                            </tr>
                        </thead>
                        <tbody>
                    {% for items in cart %}
                        <tr>
                            <td class='column1'>
                            <img src='{{items.product.product_image.url}}'
                            style="width: 130px;"/>
                            </td>
                            <td>{{items.product}}</td>
                            <td class='column2'>{{items.quantity}}</td>
                            <td class='column3'>${{items.price}}</td>
                            <td class='column4'>${{items.total_price}}</td>
                        </tr>
                    {% endfor %}
                         </tbody>
                    </table>
            {% else %}
                <h1>There is nothing here to see</h1>
            {% endif %}
        {% endwith %}
        </div>
        <div>
        </div>
    </div>
    <div class='grid table-width2 table-margin basket-total'>
        <div class='grid grid-basket-total'>
            <div>
                Total Item(s)
            </div>
            <div class='grid-text'>
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    {{total_items}}
                {% endif %}
                {% endwith %}
            </div>
            <div>
                <div>
                    Total Cost of items
                </div>
            </div>
            <div class='grid-text'>
                £{{cart.get_total_price}}
            </div>
        </div>
        <div>
            <form action='{% url "orders:checkout" %}'>
                <input type="submit" value="Checkout"/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/checkout.html
{% extends 'home/base.html' %}

{% block title %}
Checkout
{% endblock %}

{% block content %}
<form action='.' method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <input type='submit' value='Buy'>
</form>


{% endblock %}

orders/templates/orders/order_history.html
{% extends 'home/base.html' %}

{% block title %}
Order History
{% endblock %}

{% block content %}
<p>
    <table style="100%">
        <tr>
            <th>Order Number</th>
            <th>Date</th>
            <th>Total Cost</th>
        </tr>
    {% for order in order_history %}
        <tr>
            <td><a href='{% url "orders:order_history_detail" order.id %}'>
                {{order.id}}
                </a></td>
            <td>{{order.create}}</td>
            <td>{{order.total_price}}</td>
        </tr>
    {% endfor %}
    </table>
</p>
{% endblock %}

orders/templates/orders/order_history_detail.html
{% extends 'home/base.html' %}

{% block title %}
Order Item Detail
{% endblock %}

{% block content %}

<p><b>Order ID {{order.id}}</b></p>
<p><b>Total Price {order.total_price}</b></p>




<table>
    <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Price</th>
    </tr>
    {% for key, order in order_history.items %}
    <tr>
        <td>{{order.product}}</td>
        <td>{{order.price}}</td>
        <td>{{order.quantity}}</td>
        <td>{{order.get_cost}}</td>
    </tr>

    {% endfor %}
    
    
</table>



{% endblock %}